# fly.toml app configuration file generated for texbab on 2023-12-02T17:09:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "texbab"
primary_region = "arn"

[build]

[[mounts]]
  source = "pb_data"
  destination = "/pb/pb_data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 550
    soft_limit = 500

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
